#! /bin/bash


kubectl apply -f helm/service-account.yml
kubectl apply -f helm/role-binding.yml
helm init --service-account tiller --wait

# Monitoring

kubectl apply -f monitoring/namespace.yml
helm install stable/prometheus \
    --namespace monitoring \
    --name prometheus

# linkerd check --pre
# linkerd install --tls= | kubectl apply -f -

kubectl apply -f monitoring/grafana/config.yml
helm install stable/grafana \
    -f monitoring/grafana/values.yml \
    --namespace monitoring \
    --name grafana

kubectl get secret \
    --namespace monitoring \
    grafana \
    -o jsonpath="{.data.admin-password}" \
    | base64 --decode ; echo

# curl -sL https://run.linkerd.io/emojivoto.yml   | kubectl apply -f -

# kubectl get -n emojivoto deploy -o yaml   | linkerd inject -   | kubectl apply -f -


